// Subject of the landscape shown inside each state's outline on its hero page.
// Chosen to echo the state's story or its best-known scenery; edit freely.
export default {
  alabama: 'the Tennessee River winding through forested hills of northern Alabama at sunset, pine trees and sandstone bluffs in the foreground',
  alaska: 'Denali towering over autumn tundra in red and gold, a braided glacial river below, alpenglow on the snow',
  arizona: 'the Sonoran Desert near Tucson at sunset, giant saguaro cacti and ocotillo in the foreground, the Santa Catalina Mountains glowing pink',
  arkansas: 'the Buffalo National River in the Ozarks, tall limestone bluffs and autumn hardwood forest, morning mist on the water',
  california: 'the Southern California coast near San Diego at golden hour, rolling surf, sandstone cliffs and a few palm trees',
  colorado: 'the Rocky Mountains with golden aspen groves around a still alpine lake reflecting snow-dusted peaks',
  connecticut: 'the Connecticut shoreline on Long Island Sound, salt marsh and rocky inlets, a small white lighthouse at dawn',
  delaware: 'Cape Henlopen dunes and beach grass on Delaware Bay at sunrise, calm water and soft pink sky',
  florida: 'the Florida Keys at sunset, turquoise shallows, mangrove islands and a long bridge vanishing to the horizon',
  georgia: 'a Georgia peach orchard heavy with ripe fruit on rolling Piedmont hills, warm late-afternoon light',
  hawaii: 'the green volcanic cliffs of the Nā Pali Coast above a turquoise Pacific, palms and a soft tropical sunset',
  idaho: 'the Sawtooth Mountains reflected in an alpine lake, pine forest and wildflowers in the foreground',
  illinois: 'the Chicago skyline seen across Lake Michigan at golden hour, calm water and glowing clouds',
  indiana: 'Indiana farmland in autumn, a red barn among golden cornfields and a line of hardwood trees',
  iowa: 'rolling Iowa cornfields under a big summer sky at sunset, a gravel road and a white farmhouse in the distance',
  kansas: 'the Kansas Flint Hills tallgrass prairie with a field of sunflowers under towering sunset clouds',
  kentucky: 'Kentucky bluegrass horse country, black plank fences over rolling green hills, morning fog and sunrise',
  louisiana: 'a Louisiana bayou at golden hour, bald cypress trees draped in Spanish moss reflected in still water',
  maine: 'the rocky coast of Maine with a white lighthouse on the cliffs, crashing surf and pine trees at sunrise',
  maryland: 'the Chesapeake Bay at sunrise, marsh grass, wooden pilings and a traditional skipjack sailboat on calm water',
  massachusetts: 'Cape Cod dunes and beach grass leading to a lighthouse, soft ocean light at the end of the day',
  michigan: 'the Pictured Rocks cliffs on Lake Superior, colourful sandstone above clear turquoise water, birch forest on top',
  minnesota: 'a northwoods lake in Minnesota at dawn, wild rice beds near the shore, pines and mist over the water',
  mississippi: 'the Mississippi River at sunset seen through live oaks, the wide river glowing gold',
  missouri: 'the Gateway Arch in St. Louis above the Mississippi River at sunset, glowing sky reflected in the river',
  montana: 'Glacier National Park, a turquoise mountain lake below jagged peaks, wildflowers under a vast Montana sky',
  nebraska: 'the Nebraska prairie with Chimney Rock rising above golden grass, wide sky with sunset clouds',
  nevada: 'the red sandstone formations of the Valley of Fire at sunset, desert floor glowing orange and pink',
  'new-hampshire': 'the White Mountains of New Hampshire in peak autumn foliage, a covered bridge over a rocky river',
  'new-jersey': 'the Jersey Shore at sunrise, a wooden boardwalk, beach dunes and gentle waves',
  'new-mexico': 'New Mexico high desert at sunset, red mesas and the Sangre de Cristo Mountains, an adobe wall with hanging red chile ristras',
  'new-york': 'the Mohawk Valley in upstate New York in autumn, rolling hills of orange and red maples around a winding river',
  'north-carolina': 'the Blue Ridge Mountains of North Carolina at sunrise, layers of blue ridges fading into the haze',
  'north-dakota': 'the North Dakota badlands of Theodore Roosevelt National Park, striped buttes and prairie at golden hour',
  ohio: 'the Cincinnati skyline and the Roebling Suspension Bridge over the Ohio River at dusk, warm city lights on the water',
  oklahoma: 'the Oklahoma red-dirt prairie with golden wheat fields under a dramatic sunset sky, the Wichita Mountains on the horizon',
  oregon: 'the Oregon coast at Cannon Beach, Haystack Rock in the surf at sunset, wet sand reflecting the sky',
  pennsylvania: 'the Philadelphia skyline from the Schuylkill River at dusk, the historic boathouses lit along the bank',
  'rhode-island': 'Narragansett Bay in Rhode Island, sailboats on blue water and a lighthouse on a rocky point at golden hour',
  'south-carolina': 'the South Carolina Lowcountry, a tidal creek winding through marsh grass, live oaks with Spanish moss at sunset',
  'south-dakota': 'the South Dakota Badlands at sunset, layered pink and gold rock spires under a wide sky',
  tennessee: 'the Great Smoky Mountains of Tennessee at sunrise, blue mist between forested ridges',
  texas: 'the Texas Hill Country in spring, fields of bluebonnets around a spreading live oak, big blue sky',
  utah: 'Delicate Arch in Utah at sunset, red rock glowing against snow-capped La Sal Mountains',
  vermont: 'Vermont in autumn, a red barn and sugar maples in full colour, an apple orchard on the green hills',
  virginia: 'the Shenandoah Valley from the Blue Ridge Parkway at sunset, farmland and ridges in soft light',
  washington: 'Mount Rainier above alpine wildflower meadows, evergreen forest and a clear sky at golden hour',
  'west-virginia': 'the New River Gorge in West Virginia in autumn, the arch bridge above a misty river canyon',
  wisconsin: 'Wisconsin dairy country, red barns and silos on rolling green hills, Lake Michigan shoreline in the distance',
  wyoming: 'the Grand Teton range above the Snake River at sunrise, a clear trout stream and sagebrush in the foreground',
};
