// Landscape inside each state's outline on its hero page.
// Client: the scene must follow the environment described in that state's story,
// and the pictures must vary — so each entry fixes its own season and time of day.
// { scene: what is shown (from the story), light: season + time of day }
export default {
  alabama: { scene: 'the Tennessee River bending west through the wooded hills of the Tennessee Valley near Decatur, a big sycamore by the water', light: 'late summer, sunset' },
  alaska: { scene: 'the western coast of Alaska where the Bering Sea meets snow-covered tundra, drifting sea ice and an endless sky', light: 'deep winter, low sun at midday with long blue shadows and a pastel sky' },
  arizona: { scene: 'the Sonoran Desert around old Tucson, saguaros and mesquite, the Santa Catalina Mountains behind', light: 'spring, clear bright morning with brittlebush and saguaro blossoms in bloom' },
  arkansas: { scene: 'a slow muddy bend of the White River in the Arkansas Delta, bald cypress at the water’s edge and flat cotton fields beyond', light: 'high summer, hazy late afternoon with towering white cumulus clouds' },
  california: { scene: 'the rocky Pacific coast of Baja and San Diego, wooden fishing boats pulled up on a sandy cove and cold surf', light: 'early summer dawn, marine-layer fog lifting off the water' },
  colorado: { scene: 'a gold-rush valley in the Colorado Rockies, weathered mine headframe and log cabins below snowy peaks', light: 'winter afternoon after fresh snow, crisp deep-blue sky' },
  connecticut: { scene: 'Wooster Square in New Haven, rows of blossoming cherry trees, nineteenth-century brick rowhouses and a church spire', light: 'spring, soft overcast morning' },
  delaware: { scene: 'the banks of the Delaware River with frosted marsh grass, an early colonial timber farmhouse and smokehouse with a thin line of smoke', light: 'late winter, first light with pale pink mist' },
  florida: { scene: 'the Florida Keys: turquoise shallows over coral ledges, mangrove islets and key lime trees on rocky limestone', light: 'summer, bright tropical midday with puffy clouds' },
  georgia: { scene: 'a Georgia Piedmont peach orchard on rolling hills of red clay, a dirt lane between the rows', light: 'early spring, peach trees in full pink blossom, soft morning light' },
  hawaii: { scene: 'a lush Hawaiian valley of volcanic ridges and waterfalls, taro terraces (loʻi) in the valley floor', light: 'after a passing rain, late morning with a rainbow' },
  idaho: { scene: 'the Snake River Plain: potato fields and cattle range stretching to distant mountains under a huge sky', light: 'early summer afternoon with tall white clouds' },
  illinois: { scene: 'the Chicago lakefront in 1893, the gleaming White City of the World’s Columbian Exposition and the first Ferris wheel reflected in the lagoon', light: 'summer night, buildings outlined in electric lights' },
  indiana: { scene: 'flat, black-soiled Indiana farmland on the old National Road, a red barn, windmill and a line of hardwoods', light: 'late summer morning haze over golden wheat' },
  iowa: { scene: 'rolling Iowa prairie farmland with a white farmhouse, barns and a small country church steeple', light: 'early autumn, soft overcast day over harvest-ready corn' },
  kansas: { scene: 'the open Kansas tallgrass prairie bent flat by the wind, wheat fields and a distant railroad line', light: 'spring thunderstorm rolling in, dramatic storm light breaking through' },
  kentucky: { scene: 'the Cumberland Gap and the forested ridges of the Wilderness Road', light: 'early autumn dawn, mist filling the hollows' },
  louisiana: { scene: 'old New Orleans by the Mississippi River: Jackson Square, St. Louis Cathedral and iron-lace balconies', light: 'humid summer evening at blue hour, gas lamps glowing' },
  maine: { scene: 'the rocky Gulf of Maine shore, wooden lobster boats on moorings, stacked traps and painted buoys on the granite', light: 'late autumn, cold grey dawn with sea smoke' },
  maryland: { scene: 'the Chesapeake Bay salt marsh, a skipjack under sail and crab pots on a wooden dock', light: 'high summer, glittering midday' },
  massachusetts: { scene: 'the Cape Cod tidal flats at low tide, clam beds, eelgrass, dunes and a weathered shingled cottage', light: 'spring, pastel early morning' },
  michigan: { scene: 'Michigan’s Keweenaw Peninsula copper country, an old mine shaft house among spruce above Lake Superior', light: 'mid-winter, snow-covered, cold clear afternoon' },
  minnesota: { scene: 'a Boundary Waters lake ringed with birch and pine, ripening wild rice (manoomin) beds in the shallows, a birch-bark canoe on the shore', light: 'late summer, misty dawn' },
  mississippi: { scene: 'the wide, dark, unhurried Mississippi River along the Delta, cotton fields and pecan trees on the bank', light: 'autumn, warm late afternoon' },
  missouri: { scene: 'a South St. Louis street of red-brick German bakeries and corner shops, glowing bakery windows', light: 'winter, before dawn with light snow falling' },
  montana: { scene: 'the broad Bitterroot Valley between the Bitterroot and Sapphire ranges, a herd of elk in a high meadow', light: 'early autumn morning with frost and golden cottonwoods' },
  nebraska: { scene: 'Omaha on the bend of the Missouri River, mid-century rail yards and brick warehouses along the water', light: 'late summer twilight, city lights coming on' },
  nevada: { scene: 'Virginia City on the Comstock Lode, a mining town clinging to the high-desert mountainside among sagebrush', light: 'winter morning, snow on the distant Sierra Nevada' },
  'new-hampshire': { scene: 'a New Hampshire mill town on the Merrimack River in a snowy valley below the White Mountains, brick mills and a white steeple', light: 'deep winter, blue twilight with chimney smoke' },
  'new-jersey': { scene: 'Trenton on the Delaware River in the 1850s, brick factories, rail yards and river docks', light: 'cold winter morning, steam and pale sun' },
  'new-mexico': { scene: 'a Rio Grande valley village with an adobe church, red chile ristras and cottonwoods, the Sangre de Cristo Mountains behind', light: 'autumn, clear high-desert midday, cottonwoods gold' },
  'new-york': { scene: 'the Mohawk Valley and the Erie Canal with its locks and towpath, rolling hills and the town of Utica beyond', light: 'early autumn, soft morning mist' },
  'north-carolina': { scene: 'the red clay ridges of the North Carolina Piedmont, a cleared homestead garden with tomato vines, the Blue Ridge on the horizon', light: 'summer, humid morning haze' },
  'north-dakota': { scene: 'the open Northern Plains of North Dakota, mile after flat mile of prairie with a lone farmstead', light: 'winter, wind-blown snow under a pale low sun' },
  ohio: { scene: 'Cincinnati seen across the Ohio River, the Roebling Suspension Bridge and hillside neighborhoods', light: 'spring, misty early morning' },
  oklahoma: { scene: 'Oklahoma red-dirt plains, a corn patch and prairie grass, cottonwoods along a creek', light: 'summer, hot midday with heat shimmer and a vast blue sky' },
  oregon: { scene: 'Oregon timber country, Douglas fir forest of the Coast Range above the Willamette Valley, an old sawmill by a river', light: 'soft rain with low clouds drifting through the trees' },
  pennsylvania: { scene: 'the Italian Market on South 9th Street in Philadelphia, striped awnings, crates of produce and brick rowhouses', light: 'spring, early morning sun' },
  'rhode-island': { scene: 'the Narragansett Bay shore, salt marsh, old stone walls and a field of dried cornstalks', light: 'late autumn, windy afternoon with silver light' },
  'south-carolina': { scene: 'the South Carolina Lowcountry, a tidal creek winding through salt marsh to the sea islands, live oaks with Spanish moss and old rice-field dikes', light: 'moonrise over the marsh at dusk' },
  'south-dakota': { scene: 'the high prairie of southeastern South Dakota, rolling grassland and wheat with a white wooden country church', light: 'summer, bright afternoon with cumulus clouds' },
  tennessee: { scene: 'Nashville in the 1930s, the limestone State Capitol on its hill above the city and the Cumberland River', light: 'warm summer night under a starry sky' },
  texas: { scene: 'Military Plaza in old San Antonio, Spanish colonial stone buildings, wooden tables and iron pots under strings of lanterns', light: 'spring evening at dusk, lanterns glowing' },
  utah: { scene: 'the Salt Lake Valley, pioneer log cabins and fenced fields below the Wasatch Mountains', light: 'winter, snow on everything, cold clear morning' },
  vermont: { scene: 'a Champlain Valley hillside apple orchard in Addison County, Lake Champlain and the Adirondacks beyond', light: 'early autumn harvest, crisp morning, trees heavy with red apples' },
  virginia: { scene: 'Virginia peanut fields in the Tidewater by the James River, a split-rail fence and an old farmhouse', light: 'late summer, soft afternoon' },
  washington: { scene: 'a Pacific Northwest river through an old-growth cedar forest during the salmon run', light: 'autumn, misty rainy morning, soft green light' },
  'west-virginia': { scene: 'the folded ridges of the Allegheny Mountains, a small farm with buckwheat fields in a hollow', light: 'winter, fog in the valleys and a dusting of snow on the ridges at dawn' },
  wisconsin: { scene: 'Racine on the western shore of Lake Michigan, a harbor lighthouse and frozen shoreline', light: 'early spring, ice breaking up under a crisp morning sun' },
  wyoming: { scene: 'a cold, fast trout river in Wyoming cutting through high desert and pine forest, the Wind River Range beyond', light: 'summer, clear early morning' },
};
